### ISSUE TITLE
Possible Bug in abp-select. Index out of range.

### ISSUE THREAD

**Issue by Xceno** [ghiscoding/Aurelia-Bootstrap-Plugins#11]
Hey guys, I'm using `abp-select` and fixed a bug that was causing my app to crash.
I'd provide a PR but want to make sure that it is indeed a bug and not an error on my side.

So here we go:

I've got the following collection as `this.collection` in [`AbpSelectCustomElement.prototype.getGroupedCollection`](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/blob/master/aurelia-bootstrap-select/src/abp-select.js#L213)
```
[
	{"id": -1,"group": "","groupLabel": "","option": "No selection"},
	{"id": 0,"group": "Status","groupLabel": "","option": "Done"},
	{"id": 0,"group": "Status","groupLabel": "","option": "Drafts"},
	{"id": 123,"group": "Collection 1","groupLabel": "","option": "My subcollection"},
	{"id": 234,"group": "Collection 2","groupLabel": "","option": "My other subcollection"}
]
```

This gets reduced as expected. Now we've got [this line in the template](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/blob/master/aurelia-bootstrap-select/src/abp-select.html#L11). It uses the `$index` variable, which the the source of the bug in my opinion:

```
<optgroup if.bind="util.parseBool(hasOptgroup)" repeat.for="group of getGroupedCollection()"
                  label.bind="getMappingPropertyValueFromIndex(group, $index, 'groupLabel')" 
                  data-max-options.bind="getMappingPropertyValueFromIndex(group, $index, 'maxOptions') & optional"
                  disabled.bind="getMappingPropertyValueFromIndex(group, $index, 'groupDisabled') & optional">
```
My input results in *3* groups, you pass each group into [`getMappingPropertyValueFromindex`](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/blob/master/aurelia-bootstrap-select/src/abp-select.js#L244) which uses the passed in `$index` to access it:
```
getMappingPropertyValueFromIndex(inputArray, arrayIndex, searchPropName) {
    let propertyName = this.getMappingProperty(searchPropName);
    return inputArray[arrayIndex].hasOwnProperty(propertyName) ? inputArray[arrayIndex][propertyName] : '';
  }
```
So as soon as `$index === 2` the code crashes.
I've simply fixed this by replacing `$index` with `0`.

```
<optgroup if.bind="util.parseBool(hasOptgroup)" repeat.for="group of getGroupedCollection()"
                  data-index.bind="$index"
                  label.bind="getMappingPropertyValueFromIndex(group, 0, 'groupLabel')"
                  data-max-options.bind="getMappingPropertyValueFromIndex(group, 0, 'maxOptions') & optional"
                  disabled.bind="getMappingPropertyValueFromIndex(group, 0, 'groupDisabled') & optional">
```

Please let me know what you think.

**Comment by ghiscoding** [comment]
Having a quick look at it and I would assume that you would break my code if you put the `$index` at `0`. I would rather search for the reason of why your code is crashing. If I look at your list of collection, you're providing a `groupLabel` to an empty string, this is probably not accepted by `bootstrap-select`. I would remove that property from your collection, only provide it if it's filled in. Then you also have the first object with the property `group` with again an empty string, again I'm not sure that `bootstrap-select` would be happy about it. Can you change your collection with the 2 things I said and see what happen if it still crashes.  If it still crashes, can you provided the error

**Comment by Xceno** [comment]
Ahhh I see! Thanks for your quick reply, I'll check that out and get back at you

**Comment by Xceno** [comment]
Alright, I switched the code back to `$index`, removed the empty `groupLabel` and substituted my empty `group` with a default string. However, I can still reproduce the error with this:
```
[ { "id": -1, "group": "Default", "option": "No Selection" },
  { "id": 12, "group": "Some master thing", "option": "Some sub thing"}]
```
The `arrayIndex` will be incremented to 1 and crash with the second group.
It seems right now, that each group must at least contain as much entries as the value of its index in the array for this to work.

**Comment by ghiscoding** [comment]
Can you please provide the error thrown

**Comment by Xceno** [comment]
Sorry, I forgot the message. [It crashes here](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/blob/master/aurelia-bootstrap-select/src/abp-select.js#L244)

```
Unhandled rejection TypeError: Cannot read property 'hasOwnProperty' of undefined
    at AbpSelectCustomElement.getMappingPropertyValueFromIndex (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-bootstrap-select@0.1.1/abp-select.js:309:36)
    at CallScope.evaluate (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-binding@1.2.1/aurelia-binding.js:1583:21)
    at Binding.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-binding@1.2.1/aurelia-binding.js:4919:41)
    at View.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:1453:21)
    at Repeat.addView (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating-resources@1.4.0/repeat.js:261:12)
    at ArrayRepeatStrategy._standardProcessInstanceChanged (http://localhost:30321/Aurelia/jsp…ges/npm/aurelia-templating-resources@1.4.0/array-repeat-strategy.js:113:16)
    at ArrayRepeatStrategy.instanceChanged (http://localhost:30321/Aurelia/jsp…ages/npm/aurelia-templating-resources@1.4.0/array-repeat-strategy.js:35:14)
    at Repeat.itemsChanged (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating-resources@1.4.0/repeat.js:157:21)
    at Repeat.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating-resources@1.4.0/repeat.js:122:12)
    at Controller.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3459:24)
    at View.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:1463:24)
    at If._runValueChanged (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating-resources@1.4.0/if.js:85:19)
    at If.valueChanged (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating-resources@1.4.0/if.js:40:31)
    at If.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating-resources@1.4.0/if.js:29:12)
    at Controller.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:3459:24)
    at View.bind (http://localhost:30321/Aurelia/jspm_packages/npm/aurelia-templating@1.4.2/aurelia-templating.js:1463:24)
```

**Comment by ghiscoding** [comment]
I made a quick fix to avoid the error thrown, it's only making sure that the variable exist before calling anything on it (in our case it's calling `hasOwnProperty` but if it's `undefined` it will instead return the empty string since the variable is undefined.)

I didn't test anything, just pushed the code change. Could you please test it out and see what happen.

NPM was also updated to version `0.1.2`

**Comment by Xceno** [comment]
I've updated the package and everything works fine :)
Thank you!
